### ISSUE TITLE
Feature request: add visibility conditions

### ISSUE THREAD

**Issue by raptormama** [BelegCufea/CompassHUD#1]
Many addons, and many parts of interface replacements like ElvUI, allow visiblity conditions to be set -- for example, show/hide when on a mount, in a vehicle, in combat, in a pet battle, etc.

I'd love to have the ability to set these for the HUD.

Other than that, love it! I have a nice aircraft-HUD-green compass tape at the top of my display now.

**Comment by BelegCufea** [comment]
Will look into it.

In time ... as I am not playing WoW right now.

**Comment by BelegCufea** [comment]
Why do I always forget to include issues into commit?

Should be done in v1.1.5
