### ISSUE TITLE
GetMapForQuestPOIs() doesn't return the correct uiMapID

### ISSUE THREAD

**Issue by sampconrad** [BelegCufea/CompassHUD#3]
Hello.

I believe I was able to pinpoint the issue.

When calling `C_QuestLog.GetMapForQuestPOIs()` from the Objectives Tracker, it returns the `uiMapID` for the zone the player is currently in, and NOT the `uiMapID` for the zone the quest is located at. See images below for a better explanation:

If we print the `uiMapID` for a World Quest, which CompassHUD is able to correctly place a marker on the compass for, we get this:
![image](https://github.com/user-attachments/assets/deed9a0e-4d90-4f71-a42e-1caa33b348ae)

This is the expected return, as the player is in zone 2112 and the quest is in zone 2025.

But if we print the `uiMapID` for a regular quest that is also on zone 2025, it returns zone 2112 - the same zone as the player - which is incorrect:
![image](https://github.com/user-attachments/assets/b89e1df9-88b1-441d-a66d-58867cb20480)

**Comment by sampconrad** [comment]
I was able to make some progress by doing this:

```
    else -- regular quest
      uiMapID = getMapId(questID)
      questType = questNormal

      local questsOnMap = C_QuestLog.GetQuestsOnMap(uiMapID)

      if questsOnMap then
        for _, info in ipairs(questsOnMap) do
          if info.questID == questID then
            x = info.x
            y = info.y
            break
          end
        end
      end

      print("Player uiMapId: ", playerMapId)
      print("World Quest uiMapId: ", uiMapID)
    end
```

This allowed me to correctly retrieve the information for regular quests, but since the `getMapId()` function relies on `C_QuestLog.GetMapForQuestPOIs()`, it only works if you open the Quest Log (default key "M") and track quests from there. If you try to track them from the Objectives Tracker, `C_QuestLog.GetMapForQuestPOIs()` falls into the issue described above and returns the incorrect zone ID.

![image](https://github.com/user-attachments/assets/97eec60a-4670-4acc-91f4-0ad52aa3405c)

**Comment by BelegCufea** [comment]
@sampconrad Thanks. I was not aware of this.

But I have a bigger problem. I can't extract x and y coordinates for quest POI. None of the following APIs work correctly for regular quests even when given the correct uiMapID:
- C_TaskQuest.GetQuestLocation(questID, uiMapID)
- C_QuestLog.GetNextWaypointForMap(questID, uiMapID)
- C_QuestLog.GetNextWaypoint(questID)

I will look into this in the future if I try War Within (too many real life problems right now)

**Comment by sampconrad** [comment]
> None of the following APIs work correctly for regular quests even when given the correct uiMapID:

Yeah, I noticed that. I'm curious how they're managing to do it internally because the default compass works just fine, including the behaviour you'd expect out of GetNextWaypoint(), except The [C_Navigation table doesn't even have a function that does that](https://wowpedia.fandom.com/wiki/Category:API_namespaces/C_Navigation).

![image](https://github.com/user-attachments/assets/3a553f79-4995-419e-bbda-0ac1f5ecfe81)
Options > Gameplay > Interface > Display > In Game Navigation
![image](https://github.com/user-attachments/assets/38a9374f-c07d-468d-bda7-ed1377de7b26)

**Comment by BelegCufea** [comment]
@sampconrad 

Neiter [C_SuperTrack](https://wowpedia.fandom.com/wiki/Category:API_namespaces/C_SuperTrack) :-(

Let's hope [TomTom](https://www.curseforge.com/wow/addons/tomtom) will find a way (and I will STEAL it ;-) )

**Comment by sampconrad** [comment]
With the change I mentioned above, the compass is able to track all manner of quests perfectly fine if I'm currently in the zone the quest takes place. It also starts tracking them automatically when I zone into the area. I know it's not ideal, but it's at least some of the original functionality being preserved.

I can open a PR if you'd like to check it out.

**Comment by BelegCufea** [comment]
@sampconrad OMG, sorry I am blind as a rock and can't read code.

I have made some changes to the addon and pushed a new "beta" release.
My code changes are nothing to write home about as they iterate through all zone maps looking for questID using C_QuestLog.GetQuestsOnMap and your code.
The iterations should ensure that the quest will be found regardless of the map the player is currently on. It's dirty and slow, but as it is called just once in a while, it should be fine.

Please try the new version and let me know if it works (at least a bit).

**Comment by sampconrad** [comment]
It's working great so far. Thanks, @BelegCufea!

Fingers crossed Blizzard fixes `C_QuestLog.GetNextWaypoint(questID)` on 11.02 coming out next month, so we can correctly place markers taking people through portals and such. Would be a cool update.

**Comment by sampconrad** [comment]
I've opened an issue over at https://github.com/Stanzilla/WoWUIBugs detailing our findings. It's a repo dedicated to tracking API bugs found by addon developers. Blizzard is known to monitor it, and sometimes their developers reply to issues as well.

https://github.com/Stanzilla/WoWUIBugs/issues/607

**Comment by BelegCufea** [comment]
OK, I was just playing with some APIs and found out that C_QuestLog.GetNextWaypoint and C_QuestLog.GetNextWaypointForMap are used for "portals." I have incorporated that into the addon, made some optimizations, and pushed a new version.

I have also found out that you can click on "Offered quests" on the Map. I was digging around but haven't found out how to get coordinates yet (though I can extract QuestID). Will try to add that into the addon if possible.

**Comment by BelegCufea** [comment]
OK, closing for now as it seems to work in the latest version.

**Comment by sampconrad** [comment]
FYI, I noticed you've started ripping the new quest textures from the game files and packaging them with the addon:

```
    ["Interface\\AddOns\\"..ADDON_NAME.."\\textures\\RepeatableBlue"] = "Repeatable Blue",
    ["Interface\\AddOns\\"..ADDON_NAME.."\\textures\\RepeatableGold"] = "Repeatable Gold",
```

Don't know if you're aware, but they have atlases for the new quest types available. So instead of setting textures with ``Texture:SetTexture()``, you can set an atlas with ``Texture:SetAtlas()`` and simply reference the atlas name, saving you from having to rip a bunch of textures:

![image](https://github.com/user-attachments/assets/b8e0fffe-9eed-4c1a-a0db-10d3417d3aed)


Here's a few of them:
```
"quest-recurring-available",
"quest-legendary-available",
"quest-important-available",
"AutoQuest-Badge-Campaign",
"Waypoint-MapPin-Tracked",
"MiniMap-QuestArrow",
"MiniMap-DeadArrow",
"MiniMap-VignetteArrow",
"UI-HUD-Minimap-Arrow-Guard",
"UI-HUD-ActionBar-PageUpArrow-Up",
"worldquest-Capstone",
```

There's probably an API that you can call that even returns the type of quest if not the atlas to be used already, so you can set the pin accordingly, instead of having the user manually select what pin each type of quest utilizes.

You could even check quest completion state to swap from something like ``"quest-recurring-available"``...
![image](https://github.com/user-attachments/assets/8ca8176b-a0ad-4a33-a5df-94aeb492117b)

To ``"quest-recurring-turnin"``...
![image](https://github.com/user-attachments/assets/58921d62-0066-4616-b57b-b65a397c13c2)


WeakAura has a neat little atlas visualizer with searchbar if you'd like to check what the atlas name for each texture is:
![image](https://github.com/user-attachments/assets/18f3f998-8562-4da1-b11c-96b866b4a64f)

Simplify go to any texture WA and click here:
![image](https://github.com/user-attachments/assets/9b3340f4-012c-4bab-a52e-a1b55b11d33e)
