### ISSUE TITLE
Suggestion: Support Addon Compartment

### ISSUE THREAD

**Issue by raptormama** [BelegCufea/CompassHUD#9]
The Addon Compartment is a great way to provide quick access to an addon's settings without requiring a minimap button.

I was able to add support for it to CompassHUD by adding the following to the bottom of CompassHUD.lua (the heading branch test version, but it should work in any version).

And the end result is seen below, along with a bunch of other installed addons that support it. Clicking the addon name will, in this case, open the settings page you've already created.

![compasshud-in-compartment](https://github.com/user-attachments/assets/7bce5044-58e3-459c-ad14-156284e4d883)

```local aboutText = "CompassHUD";
local mouseButtonNote = "\n\nA compass tape for your UI.";
AddonCompartmentFrame:RegisterAddon({
	text = aboutText,
	icon = "Interface/AddOns/CompassHUD/textures/icon",
	notCheckable = true,
	func = function(button, menuInputData, menu)
		Settings.OpenToCategory("CompassHUD")
	end,
	funcOnEnter = function(button)
		MenuUtil.ShowTooltip(button, function(tooltip)
			tooltip:SetText(aboutText .. mouseButtonNote)
		end)
	end,
	funcOnLeave = function(button)
		MenuUtil.HideTooltip(button)
	end,
})

**Comment by BelegCufea** [comment]
Yup, it's about time I think. While testing I am still using my [Pretty Reputation](https://www.curseforge.com/wow/addons/pretty-reputation) addon compartment entry to quickly get into options :-) I'm sooo lazy.

Minimap? Data broker?

**Comment by raptormama** [comment]
The mini map is the small map in the upper right corner of the screen; I don't know what it's called in other languages. (I think that's what you're asking?) And [here's LibDataBroker](https://github.com/tekkub/libdatabroker-1-1/).

I am now curious about Pretty Reputation and have installed it!

**Comment by BelegCufea** [comment]
OK, will do all three :-) On it right now.
